version: "3.5"

networks:
  localdev:
    name: localdev

services:
  sala:
    build: ../backend
    container_name: backend
    restart: always
    ports:
      - 4000:80
      - 4002:443
    depends_on:
      - database
    networks:
      - localdev
  database:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: backend-db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123?
      - MSSQL_TCP_PORT=1433
    ports:
      - 5003:1433
    networks:
      - localdev

